export const companyProfile = {
  name: 'Umbral',
  phone: '+34 691 29 22 45',
  email: 'nanchusss@icloud.com',
  website: 'www.umbral-premium.com',
  address: 'Barcelona, Catalunya',
  zones: 'Barcelona · Girona · Tarragona · Lleida',
};

export const adminCatalog = [
  {
    id: 'pergolas',
    name: 'Pérgolas bioclimáticas',
    coverImage: '/images/pergola_bioclimatica_p_190_principal.jpg',
    marketingHeadline: 'Arquitectura de exterior, hecha para habitar con calma.',
    marketingSummary: 'Control solar adaptable, diseño mediterráneo y acabados de alta gama para elevar el valor de cada proyecto.',
    benefits: [
      'Control solar preciso durante todo el día',
      'Materiales nobles de alta durabilidad',
      'Integración arquitectónica limpia',
      'Instalación profesional en toda Cataluña',
    ],
    collections: [
      {
        id: 'costa-brava',
        name: 'Colección Costa Brava',
        models: [
          {
            id: 'pergola-p190',
            name: 'Pérgola Bioclimática P-190',
            commercialImage: '/images/190/pergola_bioclimatica_p_190_principal.jpg',
            technicalImage: '/images/190/pergola_bioclimatica_p_190_saxun_web.png',
            offerTitle: 'Pérgola bioclimática P-190 para control solar avanzado',
            commercialDescription: 'Amplia, sólida y minimalista. Protección solar con el máximo confort.',
            commercialClaims: [
              'Arquitectura exterior de líneas puras para proyectos residenciales y contract.',
              'Protección solar y ventilación natural para uso durante todo el año.',
              'Diseñada para aportar confort, elegancia y valor a la vivienda.',
            ],
            technicalDescription: 'La pérgola P-190 incorpora una estructura de aluminio extrusionado de alta resistencia con lamas orientables de hasta 135°, ofreciendo ventilación natural, protección frente a la lluvia y un elevado confort térmico.',
            technicalBullets: [
              'Estructura de aluminio extrusionado de alta resistencia',
              'Lamas orientables de 0° a 135°',
              'Canalización de aguas pluviales por drenaje libre o solera',
              'Motorización exterior 24V con seguridad reforzada',
              'Configuraciones de 1, 2, 3, 4 columnas y sin columnas',
            ],
            featureCards: [
              {
                icon: '01',
                title: 'Cubierta transpirable',
                description: 'Lamas orientables de 0° a 135° para regular luz y ventilación.',
              },
              {
                icon: '02',
                title: 'Sellado perimetral',
                description: 'Sistema registrado para mejorar el comportamiento frente a lluvia transversal.',
              },
              {
                icon: '03',
                title: 'Materiales premium',
                description: 'Aluminio 6063 T5 y acabados de alta durabilidad para exterior.',
              },
              {
                icon: '04',
                title: 'Automatización',
                description: 'Motorización y control para una experiencia de confort diario.',
              },
            ],
            configurationOptions: ['4 columnas', '3 columnas', '2 columnas', '1 columna', 'Columna desplazada', 'Sin columnas'],
            maxDimensions: [
              'Ancho máximo ensayado: 5.600 mm',
              'Largo máximo ensayado: 7.000 mm',
              'Altura máxima: 3.000 mm',
              'Dimensión de viga: 240 mm',
              'Dimensión de columna: 160x160 mm',
            ],
            testStandards: ['EN 13659 Clase 6 ~112 Km/h', 'EN 12056-3 108 l·m²/h', 'EN 1999 Eurocode 9 ≤ 100 kg/m²'],
            basePrice: 12850,
          },
          {
            id: 'pergola-p230',
            name: 'Pérgola Bioclimática P-230',
            commercialImage: '/images/p-230/pergola_bioclimatica_p_230_web.png',
            technicalImage: '/images/p-230/saxun_p_230_campo_final.jpg',
            offerTitle: 'Pérgola bioclimática P-230 de gran prestación estructural',
            commercialDescription: 'Amplia, sólida y minimalista. Protección solar con el máximo confort.',
            commercialClaims: [
              '39,2 m² completamente diáfanos para grandes espacios exteriores.',
              'Diseñada para disfrutar del exterior durante todo el año.',
              'Seguridad, confort, diseño y elegancia en un único sistema.',
            ],
            technicalDescription: 'La pérgola P-230 incorpora una estructura de aluminio extrusionado de gran sección con lamas orientables de hasta 135°, ofreciendo excelente ventilación natural, protección frente a lluvia y alto confort térmico.',
            technicalBullets: [
              'Dimensión de viga sobredimensionada para luces amplias',
              'Drenaje integrado y control de pendientes',
              'Tipologías de montaje adaptables por proyecto',
              'Acabados Qualicoat y lacados premium',
            ],
            featureCards: [
              {
                icon: '01',
                title: 'Cubierta transpirable',
                description: 'Lamas orientables de 0° a 135° para un control solar preciso.',
              },
              {
                icon: '02',
                title: 'Sellado perimetral',
                description: 'Sistema registrado para mejorar el rendimiento ante lluvia transversal.',
              },
              {
                icon: '03',
                title: 'Materiales',
                description: 'Aluminio 6063 T5 con acabados de alta gama para exterior.',
              },
              {
                icon: '04',
                title: 'Grandes dimensiones',
                description: 'Prestación estructural optimizada para superficies de mayor envergadura.',
              },
            ],
            configurationOptions: ['4 columnas', '3 columnas', '2 columnas', 'Columna desplazada'],
            maxDimensions: [
              'Alto máximo: 3.000 mm',
              'Ancho máximo: 3.600 mm',
              'Largo máximo: 5.000 mm',
            ],
            testStandards: ['Sellado perimetral registrado', 'Canalización de aguas pluviales', 'Materiales aluminio 6063 T5'],
            basePrice: 11400,
          },
        ],
      },
    ],
  },
  {
    id: 'toldos',
    name: 'Toldos',
    coverImage: '/images/toldos.jpg',
    marketingHeadline: 'Sombra flexible para terrazas y jardines con imagen premium.',
    marketingSummary: 'Sistemas de brazos extensibles y wind screen para combinar confort diario, resistencia y presencia arquitectonica.',
    benefits: [
      'Sombra adaptable segun el uso del espacio',
      'Mecanica precisa para apertura y recogida',
      'Integracion visual sobria en fachada',
      'Variantes residenciales y contract',
    ],
    collections: [
      {
        id: 'maresme',
        name: 'Coleccion Maresme',
        models: [
          {
            id: 'terminal-cofre',
            name: 'Terminal Cofre',
            commercialImage: '/images/Terminal_Cofre.jpg',
            technicalImage: '/images/terminal_cofre_1.jpg',
            offerTitle: 'Accesorio cofre para toldos de brazos extensibles',
            technicalDescription: 'Accesorio para proteccion horizontal del tejido y mejora de durabilidad en sistemas Aura, Orus I, Orus II y Herta.',
            technicalBullets: [
              'Compatible con coleccion Maresme',
              'Incrementa la proteccion del tejido',
              'Mejora acabado visual en fachada',
              'Ideal para uso intensivo exterior',
            ],
            basePrice: 980,
          },
          {
            id: 'aura',
            name: 'Aura',
            commercialImage: '/images/aura.jpg',
            technicalImage: '/images/aura_abierto_saxun_seda.png',
            offerTitle: 'Toldo de brazos extensibles para sombra flexible',
            technicalDescription: 'Modelo versatil de extension y recogida fluida con lineas limpias para proyectos residenciales y hosteleria.',
            technicalBullets: [
              'Mecanica de apertura y cierre de alta precision',
              'Integracion estetica contemporanea',
              'Configuracion por medidas y acabados',
              'Preparado para uso diario prolongado',
            ],
            basePrice: 3250,
          },
          {
            id: 'herta',
            name: 'Herta',
            commercialImage: '/images/herta.jpg',
            technicalImage: '/images/herta_abierto_saxun_beige.png',
            offerTitle: 'Toldo robusto para exteriores exigentes',
            technicalDescription: 'Sistema de brazos extensibles con estructura reforzada, pensado para estabilidad y confort continuo.',
            technicalBullets: [
              'Estructura resistente para ciclos intensivos',
              'Sombra estable para terrazas y porches',
              'Acabado premium con presencia sobria',
              'Mantenimiento sencillo y duradero',
            ],
            basePrice: 3560,
          },
          {
            id: 'orus-i',
            name: 'Orus I',
            commercialImage: '/images/orus_i.jpg',
            technicalImage: '/images/toldos_2.jpg',
            offerTitle: 'Toldo de alto equilibrio tecnico-estetico',
            technicalDescription: 'Solucion equilibrada para control solar diario con diseno limpio y alto rendimiento en uso continuo.',
            technicalBullets: [
              'Mecanica precisa para extension uniforme',
              'Estetica limpia y discreta',
              'Excelente relacion rendimiento-confort',
              'Apto para residencial y contract',
            ],
            basePrice: 3390,
          },
          {
            id: 'orus-ii',
            name: 'Orus II',
            commercialImage: '/images/orus_i.jpg',
            technicalImage: '/images/terminal_cofre_1.jpg',
            offerTitle: 'Toldo evolucionado para proyectos premium',
            technicalDescription: 'Version avanzada con configuracion adaptable para responder a necesidades de sombra cambiantes.',
            technicalBullets: [
              'Extension adaptable segun orientacion',
              'Integracion limpia en arquitectura exterior',
              'Confort termico y visual reforzado',
              'Estructura preparada para accesorios',
            ],
            basePrice: 3720,
          },
        ],
      },
      {
        id: 'girona',
        name: 'Coleccion Girona',
        models: [
          {
            id: 'wind-screen',
            name: 'Wind Screen',
            commercialImage: '/images/previa_4_wind_screen_vista_general_copia.jpg',
            technicalImage: '/images/ws_compact_edificio.png',
            offerTitle: 'Pantalla lateral para proteccion de viento',
            technicalDescription: 'Sistema lateral para proteger zonas exteriores del viento y aumentar privacidad sin perder luz.',
            technicalBullets: [
              'Proteccion lateral efectiva en porches',
              'Acabado limpio e integrable',
              'Mayor confort de uso diario',
              'Solucion ideal para terrazas expuestas',
            ],
            basePrice: 2620,
          },
          {
            id: 'wind-screen-compact',
            name: 'Wind Screen Compact',
            commercialImage: '/images/ws_compact_principal.png',
            technicalImage: '/images/ws_compact_edificio.png',
            offerTitle: 'Version compacta para cerramiento lateral',
            technicalDescription: 'Version de menor huella visual con gran eficacia para control de viento y privacidad.',
            technicalBullets: [
              'Formato compacto de alta eficiencia',
              'Integracion en espacios contenidos',
              'Accionamiento comodo y fiable',
              'Confort lateral diario',
            ],
            basePrice: 2810,
          },
          {
            id: 'wind-screen-neo',
            name: 'Wind Screen Neo',
            commercialImage: '/images/ws_neo_web_1.png',
            technicalImage: '/images/ws_compact_principal.png',
            offerTitle: 'Wind Screen de linea contemporanea',
            technicalDescription: 'Propuesta de alto nivel estetico para cerramiento lateral con rendimiento continuo.',
            technicalBullets: [
              'Diseno actual y depurado',
              'Privacidad sin sobrecargar el espacio',
              'Proteccion frente a viento y lateralidad',
              'Solucion premium para arquitectura exterior',
            ],
            basePrice: 3090,
          },
        ],
      },
    ],
  },
  {
    id: 'cortinas',
    name: 'Cortinas de cristal',
    coverImage: '/images/cortinacristal_saxun_paisaje.png',
    marketingHeadline: 'Transparencia, proteccion y amplitud visual para exteriores.',
    marketingSummary: 'Sistemas correderos y abatibles para ampliar el uso del espacio durante todo el ano con lenguaje contemporaneo.',
    benefits: [
      'Entrada de luz natural y continuidad visual',
      'Mayor confort frente al viento',
      'Acabados premium para residencial y horeca',
      'Soluciones a medida para cada proyecto',
    ],
    collections: [
      {
        id: 'mediterraneo',
        name: 'Coleccion Mediterraneo',
        models: [
          {
            id: 'iras',
            name: 'Iras',
            commercialImage: '/images/cortina_cristal_iras_r_t7a9754.jpg',
            technicalImage: '/images/cortina_cristal_iras_r_t7a9784(1).jpg',
            offerTitle: 'Cortina de cristal corredera para espacios luminosos',
            technicalDescription: 'Sistema corredero con desplazamiento suave para dividir o abrir espacios conservando luz y elegancia.',
            technicalBullets: [
              'Movimiento paralelo silencioso',
              'Integracion arquitectonica limpia',
              'Ideal para residencial y oficinas',
              'Maximo aprovechamiento visual del exterior',
            ],
            basePrice: 4180,
          },
          {
            id: 'azur',
            name: 'Azur',
            commercialImage: '/images/cortinacristal1.png',
            technicalImage: '/images/cortinacristal2.jpg',
            offerTitle: 'Cortina abatible para balcones y porches',
            technicalDescription: 'Sistema de vidrio abatible para proyectos que buscan versatilidad espacial y acabados sobrios.',
            technicalBullets: [
              'Apertura comoda y flexible',
              'Mayor control de uso diario',
              'Estetica ligera y contemporanea',
              'Alta entrada de luz natural',
            ],
            basePrice: 3970,
          },
          {
            id: 'valles-horeca',
            name: 'Valles Horeca',
            commercialImage: '/images/cortinacristal_horeca_azur_st_post_1.jpg',
            technicalImage: '/images/cortinacristal_saxun_paisaje.png',
            offerTitle: 'Aplicacion contract para hosteleria y restauracion',
            technicalDescription: 'Solucion para terrazas horeca que combina cerramiento versatil, confort termico y transparencia.',
            technicalBullets: [
              'Pensado para uso contract intensivo',
              'Confort y proteccion climatica',
              'Integracion en pergolas y fachadas',
              'Experiencia premium para cliente final',
            ],
            basePrice: 4420,
          },
        ],
      },
    ],
  },
];

export const adminAccessoryOptions = [
  {
    id: 'none',
    name: 'Sin accesorio',
    defaultDescription: '',
    defaultPrice: 0,
    image: '/images/logo.png',
  },
  {
    id: 'motorization',
    name: 'Motorizacion premium',
    defaultDescription: 'Pack de motorizacion y control remoto con configuracion inicial incluida.',
    defaultPrice: 690,
    image: '/images/toldos.jpg',
  },
  {
    id: 'led',
    name: 'Iluminacion LED integrada',
    defaultDescription: 'Tira LED perimetral integrada con regulacion de intensidad para uso nocturno.',
    defaultPrice: 540,
    image: '/images/pergola_bioclimatica_p_190_principal.jpg',
  },
  {
    id: 'sensor-pack',
    name: 'Pack sensores clima',
    defaultDescription: 'Sensores de viento y lluvia para automatizacion de apertura/cierre.',
    defaultPrice: 420,
    image: '/images/ws_compact_principal.png',
  },
  {
    id: 'professional-installation',
    name: 'Instalación profesional',
    defaultDescription: 'Servicio de instalación profesional en obra, nivelación, ajuste final y puesta en marcha del sistema.',
    defaultPrice: 950,
    image: '/images/pergola_bioclimatica_p_190_principal.jpg',
  },
];
